[package]
name = "clob_strategy_vault"
version = "1.0.0"
authors = ["0x4d7a87c0032df24b6bb29424d1ab3e7dffa5ca6801382523883f38485c32555f"]

[addresses]
clob_strategy_vault = "_"

[dev-addresses]
clob_strategy_vault = "0x4d7a87c0032df24b6bb29424d1ab3e7dffa5ca6801382523883f38485c32555f"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.8"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

